- package-lock.json
- src/pages/project/FundingPlan.js
- src/pages/project/ProjectFundingPlan.js
- src/pages/project/Tab.css
프로젝트 올리기 페이지 수정중 
app.js header수정
> artfor_react_1030_1427

- src/pages/project/ProjectFundingPlan.js
- src/pages/project/Tab.css
- src/pages/project/Tab.js
> arfor_react_1030_1441

- src/pages/project/PFPModal.js
> jh_1030_1530

- src/pages/project/Pledges.css
- src/pages/project/Pledges.js
- src/pages/project/Tab.css
- src/pages/project/Tab.js
> artfor_react_1030_2147_junghee_Pledges.js update

- package-lock.json
- src/App.js
- src/pages/admin/AdminMain.js
- src/pages/project/Check.css
- src/pages/project/MainTab.css
- src/pages/project/Pledges.css
- src/pages/project/Pledges.js
- src/pages/users/MyProject.js
- src/pages/users/MySettings/Profile.js
- src/pages/users/MySettings/SettingsTabdiv.js
- src/pages/users/Settings.css
> artfor_react_1103_1540_junghee

- package-lock.json
> artfor_react_1103_1727_junghee

- package-lock.json
- package.json
- public/index.html
- src/pages/detail/Detail.css
- src/pages/detail/Detail.js
- src/pages/detail/DetailBottom.js
- src/pages/detail/DetailContents.js
- src/pages/detail/FundingStatus.js
- src/pages/detail/Tab.js
- src/pages/home/Home.css
- src/pages/home/Home.js
- src/pages/home/HomeList.js
- src/pages/home/NoticePrj.js
- src/pages/home/OpenExpectPrj.js
- src/stores/MainStore.js
my_1105_1616_메인페이지 DB연동(mainStore연동, 이미지제외) 및 앞단 정리, 디테일페이지 스크롤 이동 기능 및 앞단정리
> my_1105_1616_메인페이지 DB연동(mainStore연동, 이미지제외) 및 앞단 정리, 디테일페이지 스크롤 이동 기능 및 앞단정리

- src/pages/admin/AdminMain.css
- src/pages/admin/AdminMain.js
- src/pages/admin/ManageArtwork.js
- src/pages/admin/ProjectList.js
- src/pages/admin/UserTable.js
> 운영자 페이지 UI 정리_jina_1105

- src/pages/project/FundingPlan.js
> artfor_react_1106_1544

- src/Header/components/AdminMenu.js
- src/Header/components/LogoutLink.js
- src/Header/components/RightMenu.js
- src/Header/components/UserLinkMenu.js
- src/pages/login/Login.js
- src/pages/users/MyProject.js
jina_1106_로그인시 localStorage 에 토큰생성, 유저아이디 저장, 메인메뉴 바뀜 but 메인메뉴 새로고침 이슈있음
> jina_1106_로그인시 localStorage 에 토큰생성, 유저아이디 저장, 메인메뉴 바뀜 but 메인메뉴 새로고침 이슈있음

- src/pages/login/Join.js
> arfor_react_1110_1714

- src/pages/community/Coummunity.js
> artfor_2153

- src/pages/admin/UserTable.js
- src/pages/community/Coummunity.js
- src/stores/CommunityStore.js
> sh_lunchCommit

- src/pages/project/MainTab.css
- src/pages/project/MainTab.js
- src/pages/project/ProjectPlan.js
> jh_1112_1532

- src/Header/components/SearchModal.js
- src/pages/project/ProjectPlan.js
> jh_1113_1412

- src/pages/community/Coummunity.js
- src/stores/CommunityStore.js
> sh_artfor_1113_2028 댓글페이지 입력, 수정, 삭제, 읽기 완료

- src/Header/components/SearchModal.js
> jh_1113_2039

- src/Header/components/SearchModal.js
Reverts gitgsh/artfor_react#105 모달 오류 수정중
> Revert "jh_1113_2039"

- src/pages/detail/FundingStatus.js
> jh_1114_1429

- src/pages/community/Coummunity.js
sh_artfor_1114_1446 backgroundcolor 수정
> sh_artfor_1114_1446 backgroundcolor 수정

- src/pages/login/Login.js
- src/pages/users/MySettings/PasswordModal.js
> passwordModal 비밀번호 변경 수정

- src/index.js
- src/pages/users/MyProject/FundingProject.js
- src/pages/users/MyProject/LikeProject.js
- src/stores/FundingStore.js
- src/stores/LikeStore.js
> sh_마이페이지-프로젝트_1114_2131

- src/Header/components/UploadLeftMenu.js
- src/pages/users/MyProject/FundingProject.js
- src/pages/users/MyProject/LikeProject.js
- src/pages/users/MyProject/MakeProject.js
> artfor_mypage완성_1115_1316

- src/Header/components/AdminMenu.js
- src/Header/components/LeftMenu.js
- src/Header/components/LogoutLink.js
- src/Header/components/RightMenu.js
- src/Header/components/SearchModal.js
- src/Header/components/UserLinkMenu.js
> 헤더부분 수정중_1115_1532

- src/Footer/components/FooterCompany.js
- src/Footer/components/FooterContent.js
- src/Header/Header.js
- src/Header/components/LeftMenu.js
- src/Header/components/LoginLink.js
- src/Header/components/SearchModal.css
- src/Header/components/SearchModal.js
- src/Header/components/UserLinkMenu.js
- src/pages/Main/components/ProjectCard.js
- src/pages/home/NoticePrj.js
- src/pages/home/OpenExpectPrj.js
- src/pages/project/Main.css
- src/pages/project/Main.js
sh_메인 헤더, 푸터, 카드리스트 수정_1116_1337
> sh_메인 헤더, 푸터, 카드리스트 수정_1116_1337

- src/pages/project/Main.css
- src/pages/project/Main.js
> sh_프로젝트 메인 수정_1116_1821

- src/Header/components/UploadLeftMenu.js
- src/pages/detail/DetailContents.js
- src/pages/project/Check.js
- src/pages/project/FundingPlan.js
- src/pages/project/MainTab.js
- src/pages/project/PFPModal.js
- src/pages/project/ProjectFundingPlan.js
- src/pages/project/TobeRel.js
git commit -m "sh_헤더 뒤로 가기 수정_1116_2013"
> git commit -m "sh_헤더 뒤로 가기 수정_1116_2013"

- src/pages/project/ProjectFundingPlan.js
git commit -m "sh_프로젝트 기획, 공개예정 수정"
> git commit -m "sh_프로젝트 기획, 공개예정 수정"

- package-lock.json
- src/pages/login/Login.js
- src/pages/map/MapPage.js
> artfor_최종_1118_1454
